#!/usr/bin/env python3
"""Extract the native 1.12 inventory UI and a compact item texture atlas."""

from __future__ import annotations

import io
import lzma
import math
import runpy
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parent.parent
CLIENT = ROOT / "vendor/clients/stable-galmuri.epw"
PUBLIC_OUTPUT = ROOT / "public/assets/minecraft/admin-inventory"
MANIFEST_OUTPUT = ROOT / "src/generated/minecraft-item-atlas.ts"
GUI_PREFIX = "assets/minecraft/textures/gui/container/"
TEXTURE_PREFIXES = {
    "item": "assets/minecraft/textures/items/",
    "block": "assets/minecraft/textures/blocks/",
}
ATLAS_COLUMNS = 32
CELL_SIZE = 16


def load_entries() -> dict[str, bytes]:
    client_tools = runpy.run_path(str(ROOT / "scripts/build-client-font.py"))
    bundle = CLIENT.read_bytes()
    record = client_tools["read_epw_records"](bundle)[0]
    epk = lzma.decompress(
        bundle[record.data_offset : record.data_offset + record.compressed_length]
    )
    _, _, entries = client_tools["parse_epk"](epk)
    return {entry.name: entry.data for entry in entries}


def first_frame(data: bytes) -> Image.Image:
    texture = Image.open(io.BytesIO(data)).convert("RGBA")
    frame_size = min(texture.width, texture.height)
    frame = texture.crop((0, 0, frame_size, frame_size))
    if frame.size != (CELL_SIZE, CELL_SIZE):
        frame = frame.resize((CELL_SIZE, CELL_SIZE), Image.Resampling.NEAREST)
    return frame


def save_gui_textures(entries: dict[str, bytes]) -> None:
    inventory = Image.open(io.BytesIO(entries[f"{GUI_PREFIX}inventory.png"])).convert("RGBA")
    chest = Image.open(io.BytesIO(entries[f"{GUI_PREFIX}generic_54.png"])).convert("RGBA")
    inventory.crop((0, 0, 176, 166)).save(
        PUBLIC_OUTPUT / "player.png", optimize=True, compress_level=9
    )

    ender = Image.new("RGBA", (176, 167))
    ender.paste(chest.crop((0, 0, 176, 71)), (0, 0))
    ender.paste(chest.crop((0, 126, 176, 222)), (0, 71))
    ender.save(PUBLIC_OUTPUT / "ender.png", optimize=True, compress_level=9)


def save_item_atlas(entries: dict[str, bytes]) -> None:
    textures: list[tuple[str, Image.Image]] = []
    for kind, prefix in TEXTURE_PREFIXES.items():
        for path in sorted(entries):
            if not path.startswith(prefix) or not path.endswith(".png"):
                continue
            key = f"{kind}:{Path(path).stem}"
            textures.append((key, first_frame(entries[path])))

    rows = math.ceil(len(textures) / ATLAS_COLUMNS)
    atlas = Image.new("RGBA", (ATLAS_COLUMNS * CELL_SIZE, rows * CELL_SIZE))
    indexes: list[tuple[str, int]] = []
    for item_index, (key, texture) in enumerate(textures):
        x = item_index % ATLAS_COLUMNS
        y = item_index // ATLAS_COLUMNS
        atlas.paste(texture, (x * CELL_SIZE, y * CELL_SIZE), texture)
        indexes.append((key, item_index))
    atlas.save(PUBLIC_OUTPUT / "items.png", optimize=True, compress_level=9)

    lines = [
        "// Generated by scripts/build-admin-inventory-assets.py. Do not edit by hand.",
        f"export const MINECRAFT_ITEM_ATLAS_COLUMNS = {ATLAS_COLUMNS};",
        f"export const MINECRAFT_ITEM_ATLAS_ROWS = {rows};",
        "export const MINECRAFT_ITEM_TEXTURES: Readonly<Record<string, number>> = {",
    ]
    lines.extend(f'  "{key}": {index},' for key, index in indexes)
    lines.append("};")
    MANIFEST_OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(textures)} item textures into {atlas.width}x{atlas.height} atlas")


def main() -> None:
    if not CLIENT.is_file():
        raise SystemExit(f"Missing generated client: {CLIENT}")
    PUBLIC_OUTPUT.mkdir(parents=True, exist_ok=True)
    MANIFEST_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    entries = load_entries()
    save_gui_textures(entries)
    save_item_atlas(entries)


if __name__ == "__main__":
    main()
